server:
  port: 70
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern:  /static/**
  datasource:
    driver-clss-name:  com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/memo_230619?characterEncoding=UTF-8
    username: root
    password: root
    
